
IMGNAME=a.img
IMGSIZE=30
LOGFILE=qemu.log

run-iso-in-qemu-kvm:
	[[ "x$(iso)" != "x" ]]
	reset
	rm -vf "$(IMGNAME)"
	qemu-img create -f qcow2 "$(IMGNAME)" $(IMGSIZE)G
	qemu-kvm -serial stdio -m 2048 -hda "$(IMGNAME)" -cdrom "$(iso)" | tee $(LOGFILE)
	rm -vf "$(IMGNAME)"

