
IMGNAME=a.img
IMGSIZE=30
LOGFILE=qemu.log
ADMINPW=r

create-adminpw:
	openssl passwd -salt RH $(ADMINPW)

run-iso-in-qemu: create-adminpw
	[[ "x$(iso)" != "x" ]]
	qemu-img create -f qcow2 "$(IMGNAME)" $(IMGSIZE)G
	qemu-kvm -serial stdio -m 2048 -boot d -hda "$(IMGNAME)" -cdrom "$(iso)" -net user -net nic -net nic $(WITH_QEMU_ARGS) | tee $(LOGFILE)

clean:
	rm -vf "$(IMGNAME)"
